# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 22:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Credit_Card',
            fields=[
                ('Number', models.IntegerField(primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
                ('Expiry_Date', models.DateField(verbose_name='Date (m/y)')),
                ('Security_Code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('FName', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Friend_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f1', to='store.Customer')),
                ('Friend_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f2', to='store.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('Email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('FName', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
                ('Banking_Info', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Status', models.CharField(choices=[('APP', 'Approved'), ('RJ', 'Rejected'), ('PD', 'Pending')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('Feedback', models.TextField()),
                ('Cusomter_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
                ('Merchant_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('Email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('FName', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
                ('Resp_Level', models.CharField(choices=[('HI', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_Number', models.AutoField(primary_key=True, serialize=False)),
                ('Total_Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Shipping_Info', models.CharField(max_length=200)),
                ('Billing_Info', models.CharField(max_length=200)),
                ('Placed_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Brand', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=50)),
                ('Compatibility', models.TextField(blank=True)),
                ('Seller_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('Feedback', models.TextField()),
                ('Cusomter_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Product_ID',
            field=models.ManyToManyField(to='store.Product'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='Reviewed_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Moderator'),
        ),
        migrations.AddField(
            model_name='credit_card',
            name='CEmail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Cusomter_Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Product_ID',
            field=models.ManyToManyField(blank=True, to='store.Product'),
        ),
    ]
