# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Cusomter_Email',
            new_name='Customer_Email',
        ),
        migrations.RenameField(
            model_name='merchant_review',
            old_name='Cusomter_Email',
            new_name='Customer_Email',
        ),
        migrations.RenameField(
            model_name='product_review',
            old_name='Cusomter_Email',
            new_name='Customer_Email',
        ),
    ]
