# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 23:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_Card',
            fields=[
                ('Number', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(16)])),
                ('FName', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
                ('Expiry_Date', models.DateField(verbose_name='%m/%y')),
                ('Security_Code', models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(3)])),
                ('CEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
            ],
        ),
    ]
