# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170404_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='Primary',
            field=models.BooleanField(default=False),
        ),
    ]
