# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 00:10
from __future__ import unicode_literals

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('store', '0002_credit_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('Email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('FName', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
                ('Banking_Info', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=50)),
                ('Address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('Email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('FName', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
                ('Resp_Level', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='Number',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='Security_Code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merchant',
            name='Approved_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Moderator'),
        ),
    ]
