# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170403_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Brand', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=50)),
                ('Compatibility', models.TextField(blank=True)),
                ('Buyer_Email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
                ('Seller_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Merchant')),
            ],
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='Expiry_Date',
            field=models.DateField(verbose_name='Date (m/y)'),
        ),
    ]
