# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='Status',
            field=models.CharField(choices=[('APP', 'Approved'), ('RJ', 'Rejected'), ('PD', 'Pending')], default='PD', max_length=50),
        ),
    ]
