# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20170407_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='Product_ID',
        ),
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.URLField(default=''),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
