# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20170410_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_card',
            name='Expiry_Date',
            field=models.DateField(verbose_name='Date (yyyy-mm-dd)'),
        ),
    ]
