# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20170407_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='Reviewed_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Moderator'),
        ),
    ]
