# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 01:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20170403_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('Feedback', models.TextField()),
                ('Cusomter_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
                ('Merchant_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Merchant')),
            ],
        ),
    ]
