# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20170410_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_card',
            name='Expiry_Date',
        ),
        migrations.AddField(
            model_name='credit_card',
            name='ExpiryMonth',
            field=models.IntegerField(default=0, verbose_name='Expiration Month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit_card',
            name='ExpiryYear',
            field=models.IntegerField(default=18, verbose_name='Expiration Year'),
            preserve_default=False,
        ),
    ]
