# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20170407_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='Reviewed_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Moderator'),
        ),
    ]
