# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 01:44
from __future__ import unicode_literals

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merchant_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Billing_Info',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_info', to='address.Address'),
        ),
    ]
