# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cusomter_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
                ('Product_ID', models.ManyToManyField(blank=True, null=True, to='store.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Product_ID',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
