# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 02:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20170403_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Friend_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f1', to='store.Customer')),
                ('Friend_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f2', to='store.Customer')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='Product_ID',
            field=models.ManyToManyField(blank=True, to='store.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Total_Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
