# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20170403_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_card',
            name='Number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
